[tool.ruff]
line-length = 100
target-version = "py38"
respect-gitignore = true

# Enable a selection of lint rule families.
select = [
  "E",  # pycodestyle errors
  "F",  # pyflakes
  "I",  # isort
  "B",  # flake8-bugbear
  "UP", # pyupgrade
  "C90" # mccabe complexity
]

ignore = [
  # Add any rule codes to ignore here
]

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = ["F401", "I001", "E501"]
"routers/score.py" = ["E501", "C901", "E722", "I001", "F401", "B904"]
"routers/copyvio.py" = ["F401", "B904", "E501", "I001"]
"routers/citoid.py" = ["F401", "E501", "E722", "B904", "C901", "I001"]
"routers/archive.py" = ["I001", "F401", "E501"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"

[tool.ruff.lint.isort]
known-first-party = ["routers", "parsers"]
